---
title: "Day7_raster"
format: html
editor: visual
---

# Load packages

```{r}
#| message: false
library(tidyverse) # Tidyverse pkgs
library(sf) # Working with spatial objects
library(osmdata) # Download OSM data
library(cowplot) # Combine plots
library(smoothr) # Smooth edges of sf objects
library(geodata) # Elev data
library(showtext) # For custom fonts
library(terra) # Deal with DEM data
library(metR) # Tanaka contours in ggplot
library(rcartocolor) # Colour palette

showtext::showtext_auto()
showtext_opts(dpi = 600) # Makes sure the text is same res as plot
## Fonts that support Japanese characters
sysfonts::font_add_google(name = "Noto Sans JP", family = "JP1", bold.wt = 900)
sysfonts::font_add(family = "JP2", regular = "KsoShinryu.otf")
```

# Elevation data

Data for Mt. Fuji

```{r}
# Load detailed elevation data from around Canberra
elev <- geodata::elevation_3s(lon = 138.731286, lat = 35.352125,
                              path = here::here("Day7"))
```

```{r}
plot(elev)
```

Crop into bounding box

```{r}
library(terra)
bbox <- ext(138.5229074554,
            139.36748143,
            34.5,
            35.5)

fuji <- elev %>%
  terra::crop(bbox)

plot(fuji)
```

Crop into bounding box

```{r}
bbox <- ext(138,
            139.25,
            34,
            35.6)

fuji <- elev %>%
  terra::crop(bbox)

plot(fuji)
```

Convert to a data frame so we can use in ggplot

```{r}
fuji_df <- as.data.frame(fuji, xy = TRUE) %>% 
  rename(elev = srtm_64_05)
```

Use metR package to plot Tanaka contours.

```{r}
ggplot() +
  geom_contour_fill(data = fuji_df, aes(x = x, y = y, z = elev)) +
  geom_contour_tanaka(data = fuji_df, aes(x = x, y = y, z = elev),
                      breaks = seq(0, 3200, 200)) +
  coord_cartesian(xlim = c(138.6, 138.9),
                  ylim = c(34.8741851739, 35.5)) +
  theme_void() +
  theme(legend.position = "none")
```

Add some custom colours...

```{r}
ggplot() +
  geom_contour_fill(data = fuji_df, aes(x = x, y = y, z = elev)) +
  geom_contour_tanaka(data = fuji_df, aes(x = x, y = y, z = elev),
                      breaks = seq(0, 3200, 400)) +
  scale_fill_carto_c(palette = "Burg", direction = -1) +
  coord_cartesian(xlim = c(138.6, 138.9),
                  ylim = c(34.8741851739, 35.5)) +
  theme_void() +
  theme(legend.position = "none",
        plot.margin = margin(l = 30, r = 30))

```

Add ocean and coastline

```{r}
Japan_raster_sf <- terra::as.polygons(fuji, dissolve = TRUE) %>% 
  sf::st_as_sf() %>% 
  summarise()

ggplot() +
  geom_sf(data = Japan, fill = NA, colour = "black") +
  geom_sf(data = Japan_raster_sf, fill = NA, colour = "grey10") +
  coord_sf(xlim = c(138.6, 138.9),
           ylim = c(34.8741851739, 35.5)) +
  theme_void()
```

Create polygon to make border

```{r}
limits <- sf::st_bbox(c(xmin = 138.6, xmax = 138.9,
            ymin = 35.025, ymax = 35.5), crs = "EPSG:4326")

border <- sf::st_polygon(list(matrix(c(limits$xmin, limits$ymin,
                                  limits$xmin, limits$ymax,
                                  limits$xmax, limits$ymax,
                                  limits$xmax, limits$ymin,
                                  limits$xmin, limits$ymin), ncol = 2, byrow = TRUE))) %>% 
  sf::st_geometry() %>% 
  sf::st_set_crs("EPSG:4326") %>% 
  sf::st_as_sf()
```

Labels...

```{r}
mtfuji <- sf::st_point(c(138.726379, 35.363602)) %>% 
  sf::st_geometry() %>% 
  sf::st_as_sf() %>% 
  sf::st_set_crs("EPSG:4326") %>% 
  mutate(label = "3,776 m") %>% 
  bind_cols(sf::st_coordinates(.))

bay <- sf::st_point(c(138.707951, 35.078949)) %>% 
  sf::st_geometry() %>% 
  sf::st_as_sf() %>% 
  sf::st_set_crs("EPSG:4326") %>% 
  mutate(label = "Suruga    Bay<br>駿河湾") %>% 
  bind_cols(sf::st_coordinates(.))
```


```{r}
baseplot <- ggplot() +
  geom_sf(data = Japan_raster_sf, fill = NA, colour = "black", size = 0.25) +
  geom_contour_fill(data = fuji_df, aes(x = x, y = y, z = elev),
                    breaks = seq(0, 3800, 200)) +
  geom_contour_tanaka(data = fuji_df, aes(x = x, y = y, z = elev),
                      breaks = seq(0, 3800, 200)) +
  geom_richtext(data = mtfuji, aes(x = X + 0.01, y = Y + 0.01, label = label), family = "JP1", label.colour = NA, fill = NA,
                size = 2.75, hjust = 0, fontface = "bold") +
  geom_richtext(data = bay, aes(x = X, y = Y, label = label), family = "JP2", label.colour = NA, fill = NA,
                size = 3, hjust = 0.5) +
  geom_sf(data = border, fill = NA, colour = "grey10", size = 1.75) +
  scale_fill_carto_c(palette = "Burg", direction = -1) +
  coord_sf(xlim = c(limits$xmin, limits$xmax),
           ylim = c(limits$ymin, limits$ymax),
           expand = FALSE) +
  theme_void() +
  theme(legend.position = "none",
        plot.margin = margin(t = 20, b = 20, l = -50, r = 50),
        panel.background = element_rect(fill = "#3498db", colour = NA))

baseplot
```

```{r}
ggdraw() +
  #Shift slightly more left
  draw_plot(baseplot, x = -0.15, y = 0, height = 1) +
  #We'll add a textured background in PS
  theme(plot.background = element_rect(fill = NA, colour = NA),
        panel.background = element_rect(fill = NA, colour = NA))

ggsave(here::here("Day7/Day7_raw.png"), width = 7, height = 5, dpi = 600)
```







